[package]
name = "dotenv"
version = "0.14.0"
authors = ["Noemi Lapresta <noemi.lapresta@gmail.com>", "Craig Hills <chills@gmail.com>", "Mike Piccolo <mfpiccolo@gmail.com>", "Alice Maz <alice@alicemaz.com>", "Sean Griffin <sean@seantheprogrammer.com>", "Adam Sharp <adam@sharplet.me>"]
description = "A `dotenv` implementation for Rust"
homepage = "https://github.com/dotenv-rs/dotenv"
readme = "README.md"
keywords = ["environment", "env", "dotenv", "settings", "config"]
license = "MIT"
repository = "https://github.com/dotenv-rs/dotenv"
edition = "2018"

[[bin]]
name = "dotenv"
required-features = ["cli"]

[dependencies]
lazy_static = "1.0.0"
regex = "1.0"
clap = { version = "2", optional = true }

[dependencies.failure]
version = "0.1.1"
features = ["derive"]
default-features = false

[dev-dependencies]
tempfile = "3.0.0"

[features]
backtrace = ["failure/backtrace"]
cli = ["clap"]
default = ["backtrace"]
